//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Bills = new HashSet<Bill>();
            this.Products = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> age { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string position { get; set; }
        public Nullable<bool> lsAdmin { get; set; }
        public int pk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
