//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int id { get; set; }
        public int product_Id { get; set; }
        public int quantity { get; set; }
        public int bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
