//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public string descript { get; set; }
        public int quantity { get; set; }
        public int supplier_id { get; set; }
        public int account_id { get; set; }
        public int category_id { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> ShowOnPage { get; set; }
        public Nullable<int> Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
